name: 'Setup Java Environment'
description: 'Sets up Java JDK with Gradle cache and permissions'

inputs:
  debug:
    description: "THe debug option is enabled"
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
      
    - name: Print Gradle version (debug only)
      if: ${{ inputs.debug == 'true'}}
      shell: bash
      run: ./gradlew --version
