name: 'Setup Java Environment'
description: 'Sets up Java JDK with Gradle cache and permissions'

inputs:
  java-version:
    description: 'Java version to use'
    required: true
    default: '20'
  distribution:
    description: 'Java distribution to use'
    required: true
    default: 'temurin'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: gradle

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew

    - name: Print Java & Gradle version (debug only)
      if: ${{ github.event.inputs.debug == 'true' }}
      shell: bash
      run: |
        java --version
        ./gradlew --version
