name: 'Print Gradle Properties'
description: 'Prints key Gradle properties for debugging'

inputs:
  gradleFileName:
    description: "The gradle file name"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Print Version properties
      shell: bash
      run: |
        appDemoVersionCode=$(grep -E "^[^#]*APP_DEMO_VERSION_CODE=" "${{ inputs.gradleFileName }}" | cut -d'=' -f2-)
        releaseVersionName=$(grep -E "^[^#]*RELEASE_VERSION_NAME=" "${{ inputs.gradleFileName }}" | cut -d'=' -f2-)
        buildMavenSdkVersion=$(grep -E "^[^#]*BUILD_MAVEN_SDK_VERSION=" "${{ inputs.gradleFileName }}" | cut -d'=' -f2-)
        enableLocalImpl=$(grep -E "^[^#]*ENABLE_LOCAL_IMPLEMENTATION=" "${{ inputs.gradleFileName }}" | cut -d'=' -f2-)
        
        echo "APP_DEMO_VERSION_CODE=$appDemoVersionCode"
        echo "RELEASE_VERSION_NAME=$releaseVersionName"
        echo "BUILD_MAVEN_SDK_VERSION=$buildMavenSdkVersion"
        echo "ENABLE_LOCAL_IMPLEMENTATION=$enableLocalImpl"
