name: 'Print Gradle Properties'
description: 'Prints key Gradle properties for debugging'

runs:
  using: 'composite'
  steps:
    - name: Print Version properties
      shell: bash
      run: |
        ls
        gradlePropertyFileName="../../gradle.properties"
        appDemoVersionCode=$(grep -E "^[^#]*APP_DEMO_VERSION_CODE=" "$gradlePropertyFileName" | cut -d'=' -f2-)
        releaseVersionName=$(grep -E "^[^#]*RELEASE_VERSION_NAME=" "$gradlePropertyFileName" | cut -d'=' -f2-)
        buildMavenSdkVersion=$(grep -E "^[^#]*BUILD_MAVEN_SDK_VERSION=" "$gradlePropertyFileName" | cut -d'=' -f2-)
        enableLocalImpl=$(grep -E "^[^#]*ENABLE_LOCAL_IMPLEMENTATION=" "$gradlePropertyFileName" | cut -d'=' -f2-)
        
        echo "APP_DEMO_VERSION_CODE=$appDemoVersionCode"
        echo "RELEASE_VERSION_NAME=$releaseVersionName"
        echo "BUILD_MAVEN_SDK_VERSION=$buildMavenSdkVersion"
        echo "ENABLE_LOCAL_IMPLEMENTATION=$enableLocalImpl"
