name: Android Example CI (Build all flavours)

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true
      appDemo:
        type: boolean
        description: Effettuare il rilascio delle App Demo (tutti gli env) su Firebase App Distribution
        required: true
        default: true
      mavenSdk:
        type: boolean
        description: Effettuare il rilascio del SDK (tutti gli env) sul Gitlab Package Registry
        default: false

jobs:
  deliverable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check java version
        run: java --version

      - name: Gradle Version
        run: ./gradlew --version
        if: ${{ github.event.inputs.debug == 'true' }}

        ##### SDK Variant ###########

      - name: Increment SDK versionName and versionCode
        run: ./gradlew incrementMavenVersion
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      - name: Assemble sdk devRelease
        run: ./gradlew :myTestLibrary:uploadToMavenRepDevRelease
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      - name: Assemble sdk uatRelease
        run: ./gradlew :myTestLibrary:uploadToMavenRepUatRelease
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      - name: Assemble sdk preProdRelease
        run: ./gradlew :myTestLibrary:uploadToMavenRepPreProdRelease
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      - name: Assemble sdk prodRelease
        run: ./gradlew :myTestLibrary:uploadToMavenRepProdRelease
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      ##### AppDemo Variant ###########

      - name: Print AppDemo versionCode PRE incremented
        run: ./gradlew properties | grep APP_VERSION_CODE
        if: ${{ github.event.inputs.debug == 'true' }}

      - name: Increment App versionName and versionCode
        run: ./gradlew incrementVersion

      - name: Print AppDemo versionCode incremented
        run: ./gradlew properties | grep APP_VERSION_CODE
        if: ${{ github.event.inputs.debug == 'true' }}

      - name: Git Commit & Push
        run: |
            git config user.name "github-actions[bot]"
            git config user.email "{user.id}+{user.login}@users.noreply.github.com"
            git add .
            git commit -m "Updated Version"
            git push