name: Android Example CI (Build all flavours)

on:
  workflow_dispatch:
    inputs:
      appDemo:
        type: boolean
        description: Effettuare il rilascio delle App Demo (tutti gli env) su Firebase App Distribution
        required: true
        default: true
      mavenSdk:
        type: boolean
        description: Effettuare il rilascio del SDK (tutti gli env) sul Gitlab Package Registry
        default: false

jobs:
  setUp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew


      - name: Increment App versionName and versionCode
        run: ./gradlew incrementVersion

      - name: Assemble devDebug
        run: ./gradlew uploadToAppDistributionDevDebug

      - name: Assemble uatDebug
        run: ./gradlew uploadToAppDistributionUatDebug

      - name: Assemble preProdDebug
        run: ./gradlew uploadToAppDistributionPreprodDebug

      - name: Assemble prodDebug
        run: ./gradlew uploadToAppDistributionProdDebug