name: Android Example CI (Build all flavours)

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true
      appDemo:
        type: boolean
        description: Effettuare il rilascio delle App Demo (tutti gli env) su Firebase App Distribution
        required: true
        default: true
      mavenSdk:
        type: boolean
        description: Effettuare il rilascio del SDK (tutti gli env) sul Gitlab Package Registry
        default: false

jobs:
  deliverable:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Java version
        run: java --version
        if: ${{ github.event.inputs.debug == 'true' }}

      - name: Gradle Version
        run: ./gradlew --version
        if: ${{ github.event.inputs.debug == 'true' }}

        ##### SDK Variant ###########

      - name: Print SDK versionCode and versionName PRE incremented
        if: ${{ github.event.inputs.debug == 'true' && github.event.inputs.mavenSdk == 'true' }}
        run: |
          ./gradlew properties | grep SDK_VERSION_CODE
          ./gradlew properties | grep BUILD_MAVEN_SDK_VERSION

      - name: Increment SDK versionName and versionCode
        run: ./gradlew incrementMavenVersion
        if: ${{ github.event.inputs.mavenSdk == 'true' && github.event.inputs.mavenSdk == 'true' }}

      - name: Print AppDemo DK versionCode and versionName POST incremented
        if: ${{ github.event.inputs.debug == 'true' && github.event.inputs.mavenSdk == 'true'}}
        run: |
          ./gradlew properties | grep SDK_VERSION_CODE
          ./gradlew properties | grep BUILD_MAVEN_SDK_VERSION

      - name: Assemble sdk devRelease
        run: ./gradlew :myTestLibrary:uploadToMavenRepDevRelease
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      - name: Assemble sdk uatRelease
        run: ./gradlew :myTestLibrary:uploadToMavenRepUatRelease
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      - name: Assemble sdk preProdRelease
        run: ./gradlew :myTestLibrary:uploadToMavenRepPreProdRelease
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      - name: Assemble sdk prodRelease
        run: ./gradlew :myTestLibrary:uploadToMavenRepProdRelease
        if: ${{ github.event.inputs.mavenSdk == 'true' }}

      ##### AppDemo Variant ###########

      - name: Print AppDemo versionCode PRE incremented
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          ./gradlew properties | grep APP_VERSION_CODE
          ./gradlew properties | grep APP_VERSION_NAME

      - name: Increment App versionName and versionCode
        run: ./gradlew incrementVersion

      - name: Print AppDemo versionCode POST incremented
        if: ${{ github.event.inputs.debug == 'true' }}
        run: |
          ./gradlew properties | grep APP_VERSION_CODE
          ./gradlew properties | grep APP_VERSION_NAME

      - name: Git Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
          #Estrai i valori e rimuovi gli spazi extra
          APP_VERSION_NAME=$(./gradlew properties | grep "APP_VERSION_NAME" | sed 's/.*: //')
          APP_VERSION_CODE=$(./gradlew properties | grep "APP_VERSION_CODE" | sed 's/.*: //')
          SDK_VERSION_CODE=$(./gradlew properties | grep "SDK_VERSION_CODE" | sed 's/.*: //')
          BUILD_MAVEN_SDK_VERSION=$(./gradlew properties | grep "BUILD_MAVEN_SDK_VERSION" | sed 's/.*: //')

          # Crea il messaggio di commit usando le variabili
          GIT_COMMIT_MESSAGE="build(release): AppDemo: versionName: $APP_VERSION_NAME, versionCode: $APP_VERSION_CODE. SDK: versionName: $BUILD_MAVEN_SDK_VERSION, versionCode: $SDK_VERSION_CODE. Maven version: $BUILD_MAVEN_SDK_VERSION"
      
          git add .
          git commit -m "$GIT_COMMIT_MESSAGE"
          git push


      - name: Git Tag
        if: ${{ github.event.inputs.mavenSdk == 'true' }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
          GIT_TAG_NAME=$(./gradlew properties | grep "BUILD_MAVEN_SDK_VERSION" | sed 's/.*: //')
          
          git tag $GIT_TAG_NAME
          git push origin $GIT_TAG_NAME
