name: Android Example CI (Build all flavours)

on:
  workflow_dispatch:

jobs:
  setUp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble devDebug
        run: ./gradlew assembleDevDebug

      - name: Assemble prodDebug
        run: ./gradlew assembleProdDebug