name: Delete GitHub Package Registry and Release

on:
  workflow_dispatch:
    inputs:
      versionToDelete:
        type: string
        description: Specificare la versione da cancellare
        required: true

env:
  PACKAGE_NAME: "com.pditta.githubactions.mytestlibrary"

jobs:
  delete-package-registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [ dev-release, uat-release, preProd-release, prod-release ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete PKG Registry ${{ env.VERSION_TO_DELETE }}
        env:
          VERSION_TO_DELETE: "${{ inputs.versionToDelete }}-${{ matrix.flavour }}"
        run: python ./github/scripts/delete_pkg_registry.py --token ${{ secrets.GITHUB_TOKEN }} --version ${{ env.VERSION_TO_DELETE }}

  delete-release:
    runs-on: ubuntu-latest
    needs: delete-package-registry
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete Release ${{ inputs.versionToDelete }}
        run: python ./github/scripts/delete_release.py --repository ${{ github.repository }} --tag ${{ inputs.versionToDelete }} --token ${{ secrets.GITHUB_TOKEN }}
  
  remove-tag:
    runs-on: ubuntu-latest
    needs: delete-release
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Git
        uses: ./.github/actions/setup-git

      - name: Check if Tag ${{ inputs.versionToDelete }} Exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ inputs.versionToDelete }}"; then
            echo "TAG_EXISTS=true" >> $GITHUB_OUTPUT
          else
            echo "TAG_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Delete Git Tag ${{ inputs.versionToDelete }}
        if: ${{ steps.check_tag.outputs.TAG_EXISTS == 'true' }}
        run: |
          git push origin --delete ${{ inputs.versionToDelete }}