name: Python Example

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true


jobs:
  python-version:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python dependencies
        run: pip install requests

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Controlla versione Python
        run: python scripts/check_python_version.py