name: Test delete snippets

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true

env:
  PACKAGE_NAME: "com.pditta.githubactions.mytestlibrary"
  VERSION_PREFIX: "25.03.0.20"

jobs:
  clean-package-registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [ dev-release, uat-release, preprod-release, prod-release ]
    steps:
      - name: Delete ${{ env.VERSION_TO_DELETE }}
        id: delete_pkg_registry
        env:
          VERSION_TO_DELETE: $VERSION_PREFIX-${{ matrix.flavour }}
        run: |
          # Ottieni tutte le versioni del pacchetto
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/user/packages/maven/$PACKAGE_NAME/versions")

          # Estrai l'ID della versione specifica (cerca per il nome della versione)
          version_id=$(echo "$response" | jq -r ".[] | select(.name == \"$VERSION\") | .id")
          
          # Verifica se abbiamo trovato l'ID
          if [ "$version_id" != "null" ]; then
            echo "La versione $VERSION esiste, procedo con la cancellazione."
            # Cancella la versione usando l'ID
            curl -X DELETE \
                 -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                 "https://api.github.com/user/packages/maven/$PACKAGE_NAME/versions/$version_id"
          else
            echo "La versione $VERSION non esiste, niente da cancellare."
          fi