name: Test

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: false
      increment_version:
          type: boolean
          description: Incrementa la versione dell'app e del SDK
          default: true
      upload_app_demo:
          type: boolean
          description: Upload App Demo
          default: true
      upload_app_sdk:  
          type: boolean
          description: Upload SDK
          default: true

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Verify inputs parameters
        run: |
          python scripts/inputs_verification.py --uploadAppDemo ${{ github.event.inputs.upload_app_demo }} --uploadSdk ${{ github.event.inputs.upload_app_sdk }} --incrementVersion ${{ github.event.inputs.increment_version }}
    