name: test snippets

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true

env:
  GRADLE_PROPERTIES_FILENAME: "gradle.properties"

jobs:
  create-branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.create_branch.outputs.branch_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push new branch
        id: create_branch
        run: |
          PACKAGE_NAME="com.pditta.githubactions.mytestlibrary"
          VERSION="25.03.0.20-prod-release"
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/user/packages/maven/$PACKAGE_NAME/versions")
          echo "$response"