name: test snippets

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: false
      incrementVersion:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test composite
        run: |
          ls
          pwd
      - name: Test composite
        uses: ./action.yml
