name: test snippets

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true

env:
  GRADLE_PROPERTIES_FILENAME: "gradle.properties"

jobs:
  create-branch:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.create_branch.outputs.branch_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        uses: ./.github/actions/setup-git

      - name: Create and push new branch
        id: create_branch
        run: |
          NEW_BRANCH="creating-release-$(date +%Y%m%d-%H%M%S)"
          git checkout -b "$NEW_BRANCH"
          git push origin "$NEW_BRANCH"
          echo "branch_name=$NEW_BRANCH" >> $GITHUB_OUTPUT
          echo "New branch $NEW_BRANCH created and pushed"

  testing:
    needs: create-branch
    runs-on: ubuntu-latest
    steps:

      - name: Print Java (debug only)
        shell: bash
        run: ls -lrt .github/actions

      - name: Checkout branch ${{ needs.create-branch.outputs.branch_name }}
        uses: ./.github/actions/setup-branch
        with:
          ref: ${{ needs.create-branch.outputs.branch_name }}
          debug: ${{ github.event.inputs.debug }}

          

    
