name: test snippets

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Test composite
        if: ${{ github.event.inputs.debug == 'true'}}
        uses: ./.github/workflows/action.yml
