name: Test delete snippets

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: Printa dei valori che aiutano il debug
        default: true

env:
  PACKAGE_NAME: "com.pditta.githubactions.mytestlibrary"
  VERSION_PREFIX: "25.03.0.20"

jobs:
  clean-package-registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavour: [ dev-release, uat-release, preProd-release, prod-release ]
    steps:
      - name: Delete ${{ env.VERSION_TO_DELETE }}
        id: delete_pkg_registry
        env:
          VERSION_TO_DELETE: ${{ env.VERSION_PREFIX }}-${{ matrix.flavour }}
        shell: bash
        run: |
          # Ottieni tutte le versioni del pacchetto
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/user/packages/maven/$PACKAGE_NAME/versions")
          
          echo "$response"
          
          # Estrai l'ID della versione specifica (cerca per il nome della versione)
          version_id=$(echo "$response" | jq -r ".[] | select(.name == \"$VERSION_TO_DELETE\") | .id")
          
          echo "$version_id"
          
          # Verifica se abbiamo trovato l'ID
          if [ "$version_id" != "null" ]; then
            echo "La versione $VERSION_TO_DELETE esiste, procedo con la cancellazione."
          
            delete_response=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE \
                                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                "https://api.github.com/user/packages/maven/$PACKAGE_NAME/versions/$version_id")
          
            if [ "$delete_response" -eq 204 ]; then
              echo "La versione $VERSION_TO_DELETE è stata cancellata con successo."
            elif [ "$delete_response" -eq 404 ]; then
              echo "Errore: La versione $VERSION_TO_DELETE non è stata trovata per la cancellazione."
              exit 1
            else
              echo "Errore nella cancellazione. Codice di stato: $delete_response"
              exit 1
            fi
          else
            echo "La versione $VERSION_TO_DELETE non esiste, niente da cancellare."
          fi